# Generated by Django 2.2.6 on 2020-03-17 20:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='Please_choose_all_that_apply',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Therapy/or other mental health services', 'Therapy/or other mental health services'), ('Sezizures', 'Sezizures'), ('Heart Issues', 'Heart Issues'), ('Have dependencies', 'Have dependencies'), ('Take prescription drugs', 'Take prescription drugs'), ('Diabetes', 'Diabetes'), ('High Blood Pressure', 'High Blood Pressure')], default='Unspecified', max_length=100),
        ),
    ]
