# Generated by Django 2.2.6 on 2019-11-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(blank=True, max_length=50)),
                ('female', models.CharField(blank=True, max_length=50)),
                ('prefernottosay', models.CharField(blank=True, max_length=50)),
                ('a18to21', models.CharField(blank=True, max_length=50)),
                ('a25to34', models.CharField(blank=True, max_length=50)),
                ('a35to44', models.CharField(blank=True, max_length=50)),
                ('a45to54', models.CharField(blank=True, max_length=50)),
                ('pyes', models.CharField(blank=True, max_length=50)),
                ('pno', models.CharField(blank=True, max_length=50)),
                ('rphs', models.CharField(blank=True, max_length=50)),
                ('pgc', models.CharField(blank=True, max_length=50)),
                ('vacineflu', models.CharField(blank=True, max_length=50)),
                ('prevs', models.CharField(blank=True, max_length=50)),
                ('prenatal', models.CharField(blank=True, max_length=50)),
                ('obgyn', models.CharField(blank=True, max_length=50)),
                ('keepdoctor', models.CharField(blank=True, max_length=50)),
                ('usespecialist', models.CharField(blank=True, max_length=50)),
                ('emergency', models.CharField(blank=True, max_length=50)),
                ('hd', models.CharField(blank=True, max_length=50)),
                ('cancer', models.CharField(blank=True, max_length=50)),
                ('preg', models.CharField(blank=True, max_length=50)),
                ('diabetes', models.CharField(blank=True, max_length=50)),
                ('substance', models.CharField(blank=True, max_length=50)),
                ('hiv', models.CharField(blank=True, max_length=50)),
                ('depression', models.CharField(blank=True, max_length=50)),
                ('anxiety', models.CharField(blank=True, max_length=50)),
                ('other', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
