# Generated by Django 3.0.1 on 2020-03-17 20:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='Please_choose_all_that_apply',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mental Health Conditions', 'Mental Health Conditions'), ('Respiratory Illnesses', 'Respiratory Illnesses'), ('Heart condition(s)', 'Heart Condition(s)'), ('Have dependencies', 'Have dependencies'), ('Take prescription drugs', 'Take prescription drugs'), ('Diabetes', 'Diabetes'), ('Physical condition(s)', 'Physical condition(s)'), ('Chronic Condition(s)', 'Chronic Condition(s)'), ('Disabled', 'Disabled'), ('Serious illnesses and disorders(HIV/Aids, Cancer ,Influenza, Scoliosis, Epilepsy, etc..)', 'Serious illnesses and disorders(HIV/Aids, Cancer ,Influenza, Scoliosis, Epilepsy, etc..)')], default='Unspecified', max_length=100),
        ),
    ]
