# Generated by Django 2.2.6 on 2019-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='a18to21',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='a25to34',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='a35to44',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='a45to54',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='anxiety',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='cancer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='depression',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='female',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='hd',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='hiv',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='keepdoctor',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='male',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='obgyn',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='other',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pgc',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pno',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='prefernottosay',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='preg',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='prenatal',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='prevs',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pyes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='rphs',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='usespecialist',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='vacineflu',
        ),
        migrations.AddField(
            model_name='questions',
            name='questionstoget',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PNTS', 'Prefer not to say'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('Yes', 'Yes'), ('No', 'No'), ('Regular physicals and health screenings', 'Regular physicals and health screenings'), ('Prescription drug coverage (brand name and/or generic)', 'Prescription drug coverage (brand name and/or generic)'), ('Get routine vaccines or flu shots?', 'Get routine vaccines or flu shots?'), ('Preventative services', 'Preventative services'), ('Prenatal/Maternity services', 'Prenatal/Maternity services'), ('OB-GYN', 'OB-GYN'), ('Keeping your doctor', 'Keeping your doctor'), ('Use of specialists', 'Use of specialists'), ('Emergency and hospital care', 'Emergency and hospital care'), ('Heart Disease (Cardiovascular Disease)', 'Heart Disease (Cardiovascular Disease)'), ('Cancer', 'Cancer'), ('Pregnancy', 'Pregnancy'), ('Diabetes (Type 1, Type 2, or Gestational)', 'Diabetes (Type 1, Type 2, or Gestational)'), ('Substance absue issues (drugs (illicit or prescription) and/or alcohol)', 'Substance absue issues (drugs (illicit or prescription) and/or alcohol)'), ('HIV/AIDS', 'HIV/AIDS'), ('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Other mental health disorders (may include but not limited to: Bipolar Disorder, Attention-Deficit/Hyperactivity Disorder (ADD or ADHD), Schizophrenia, Autism, Borderline personality disorder (BPD), Dissociative Disorders, Eating Disorders, Posttraumatic Stress Disorder (PTSD)))', 'Other mental health disorders (may include but not limited to: Bipolar Disorder, Attention-Deficit/Hyperactivity Disorder (ADD or ADHD), Schizophrenia, Autism, Borderline personality disorder (BPD), Dissociative Disorders, Eating Disorders, Posttraumatic Stress Disorder (PTSD)))')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
