# Generated by Django 2.2.6 on 2020-03-17 20:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0002_auto_20200317_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='Please_choose_all_that_apply',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Depression/or other mental health conditions', 'Depression/or other mental health conditions'), ('Respiratory Illnesses', 'Respiratory Illnesses'), ('Heart condition(s)', 'Heart Condition(s)'), ('Have dependencies', 'Have dependencies'), ('Take prescription drugs', 'Take prescription drugs'), ('Diabetes', 'Diabetes'), ('Physical condition(s)', 'Physical condition(s)'), ('Chronic Condition(s)', 'Chronic Condition(s)'), ('Disabled', 'Disabled'), ('Serious illnesses and disorders(HIV/Aids, Cancer ,Influenza, Scoliosis, Epilepsy, etc..)', 'Serious illnesses and disorders(HIV/Aids, Cancer ,Influenza, Scoliosis, Epilepsy, etc..)')], default='Unspecified', max_length=100),
        ),
    ]
