# Generated by Django 3.0.1 on 2020-03-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0003_auto_20200317_2020'),
        ('chooseplan', '0002_auto_20200317_1325'),
    ]

    operations = [
    ]
