# Generated by Django 2.2.6 on 2019-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0003_auto_20191108_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questionstoget',
        ),
        migrations.AddField(
            model_name='questions',
            name='Age',
            field=models.CharField(choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_currently_taking_pescribed_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Has_a_doctor_notified_you_as_a_candidate_for',
            field=models.CharField(choices=[('Cataract Surgery', 'Cataract Surgery'), ('Knee Replacement', 'Knee Replacement'), ('Hip Replacement', 'Hip Replacement')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Select_all_conditions_you_have_been_diagnosed_with',
            field=models.CharField(choices=[('Heart Disease (Cardiovascular Disease)', 'Heart Disease (Cardiovascular Disease)'), ('Cancer', 'Cancer'), ('Pregnancy', 'Pregnancy'), ('Diabetes (Type 1, Type 2, or Gestational)', 'Diabetes (Type 1, Type 2, or Gestational)'), ('Substance absue issues (drugs (illicit or prescription) and/or alcohol)', 'Substance absue issues (drugs (illicit or prescription) and/or alcohol)'), ('HIV/AIDS', 'HIV/AIDS'), ('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Other mental health disorders (may include but not limited to: Bipolar Disorder, Attention-Deficit/Hyperactivity Disorder (ADD or ADHD), Schizophrenia, Autism, Borderline personality disorder (BPD), Dissociative Disorders, Eating Disorders, Posttraumatic Stress Disorder (PTSD)))', 'Other mental health disorders (may include but not limited to: Bipolar Disorder, Attention-Deficit/Hyperactivity Disorder (ADD or ADHD), Schizophrenia, Autism, Borderline personality disorder (BPD), Dissociative Disorders, Eating Disorders, Posttraumatic Stress Disorder (PTSD)))')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Which_services_are_most_important_for_you_in_a_health_plan',
            field=models.CharField(choices=[('Regular physicals and health screenings', 'Regular physicals and health screenings'), ('Prescription drug coverage (brand name and/or generic)', 'Prescription drug coverage (brand name and/or generic)'), ('Get routine vaccines or flu shots?', 'Get routine vaccines or flu shots?'), ('Preventative services', 'Preventative services'), ('Prenatal/Maternity services', 'Prenatal/Maternity services'), ('OB-GYN', 'OB-GYN'), ('Keeping your doctor', 'Keeping your doctor'), ('Use of specialists', 'Use of specialists'), ('Emergency and hospital care', 'Emergency and hospital care')], default=0, max_length=150),
            preserve_default=False,
        ),
    ]
