# Generated by Django 2.2.6 on 2019-11-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0008_auto_20191108_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Has_a_doctor_notified_you_as_a_candidate_for',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Select_all_conditions_you_have_been_diagnosed_with',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Which_services_are_most_important_for_you_in_a_health_plan',
        ),
        migrations.AddField(
            model_name='healthcare_categories',
            name='formSubmissions',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='chooseplan.questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_a_candidate_for_cataract_surgery',
            field=models.CharField(blank=True, choices=[('Yes', '44'), ('No', '45')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_a_candidate_for_hip_replacement',
            field=models.CharField(blank=True, choices=[('Yes', '48'), ('No', '49')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_a_candidate_for_knee_replacement',
            field=models.CharField(blank=True, choices=[('Yes', '46'), ('No', '47')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_diabetic',
            field=models.CharField(blank=True, choices=[('Yes', '32'), ('No', '33')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_diagnosed_with_cancer',
            field=models.CharField(blank=True, choices=[('Yes', '28'), ('No', '29')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_diagnosed_with_heart_disease',
            field=models.CharField(blank=True, choices=[('Yes', '26'), ('No', '27')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_pregnant',
            field=models.CharField(blank=True, choices=[('Yes', '30'), ('No', '31')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_get_routine_vaccines_or_flu_shots',
            field=models.CharField(blank=True, choices=[('Yes', '12'), ('No', '13')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_OBGYN_services',
            field=models.CharField(blank=True, choices=[('Yes', '18'), ('No', '19')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_help_with_other_mental_health_disorders',
            field=models.CharField(blank=True, choices=[('Yes', '42'), ('No', '43')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_help_with_substance_abuse',
            field=models.CharField(blank=True, choices=[('Yes', '34'), ('No', '35')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_prenatal_maternity_services',
            field=models.CharField(blank=True, choices=[('Yes', '16'), ('No', '17')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_to_see_various_specialists',
            field=models.CharField(blank=True, choices=[('Yes', '22'), ('No', '23')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_treatement_for_HIV_or_Aids',
            field=models.CharField(blank=True, choices=[('Yes', '36'), ('No', '37')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_treatment_for_anxiety',
            field=models.CharField(blank=True, choices=[('Yes', '40'), ('No', '41')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_need_treatment_for_depression',
            field=models.CharField(blank=True, choices=[('Yes', '38'), ('No', '39')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_often_use_preventative_services',
            field=models.CharField(blank=True, choices=[('Yes', '14'), ('No', '15')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_receive_regular_physicals_and_health_screenings',
            field=models.CharField(blank=True, choices=[('Yes', '10'), ('No', '11')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_want_to_keep_your_current_doctor',
            field=models.CharField(blank=True, choices=[('Yes', '20'), ('No', '21')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Is_emergency_care_or_hospital_care_a_priority',
            field=models.CharField(blank=True, choices=[('Yes', '24'), ('No', '25')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Age',
            field=models.CharField(blank=True, choices=[('18-24', '4'), ('25-34', '5'), ('35-44', '6'), ('45-54', '7')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_currently_taking_pescribed_medication',
            field=models.CharField(blank=True, choices=[('Yes', '8'), ('No', '9')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', '1'), ('Female', '2'), ('Prefer not to say', '3')], max_length=500),
        ),
    ]
