# Generated by Django 2.2.6 on 2019-11-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0009_auto_20191108_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Age',
            field=models.CharField(blank=True, choices=[('4', '18-24'), ('5', '25-34'), ('6', '35-44'), ('7', '45-54')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_cataract_surgery',
            field=models.CharField(blank=True, choices=[('44', 'Yes'), ('45', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_hip_replacement',
            field=models.CharField(blank=True, choices=[('48', 'Yes'), ('49', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_knee_replacement',
            field=models.CharField(blank=True, choices=[('46', 'Yes'), ('47', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_currently_taking_pescribed_medication',
            field=models.CharField(blank=True, choices=[('8', 'Yes'), ('9', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diabetic',
            field=models.CharField(blank=True, choices=[('32', 'Yes'), ('33', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diagnosed_with_cancer',
            field=models.CharField(blank=True, choices=[('28', 'Yes'), ('29', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diagnosed_with_heart_disease',
            field=models.CharField(blank=True, choices=[('26', 'Yes'), ('27', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_pregnant',
            field=models.CharField(blank=True, choices=[('30', 'Yes'), ('31', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_get_routine_vaccines_or_flu_shots',
            field=models.CharField(blank=True, choices=[('12', 'Yes'), ('13', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_OBGYN_services',
            field=models.CharField(blank=True, choices=[('18', 'Yes'), ('19', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_help_with_other_mental_health_disorders',
            field=models.CharField(blank=True, choices=[('42', 'Yes'), ('43', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_help_with_substance_abuse',
            field=models.CharField(blank=True, choices=[('34', 'Yes'), ('35', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_prenatal_maternity_services',
            field=models.CharField(blank=True, choices=[('16', 'Yes'), ('17', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_to_see_various_specialists',
            field=models.CharField(blank=True, choices=[('22', 'Yes'), ('23', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_treatement_for_HIV_or_Aids',
            field=models.CharField(blank=True, choices=[('36', 'Yes'), ('37', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_treatment_for_anxiety',
            field=models.CharField(blank=True, choices=[('40', 'Yes'), ('41', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_treatment_for_depression',
            field=models.CharField(blank=True, choices=[('38', 'Yes'), ('39', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_often_use_preventative_services',
            field=models.CharField(blank=True, choices=[('14', 'Yes'), ('15', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_receive_regular_physicals_and_health_screenings',
            field=models.CharField(blank=True, choices=[('10', 'Yes'), ('11', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_want_to_keep_your_current_doctor',
            field=models.CharField(blank=True, choices=[('20', 'Yes'), ('21', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Prefer not to say')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Is_emergency_care_or_hospital_care_a_priority',
            field=models.CharField(blank=True, choices=[('24', 'Yes'), ('25', 'No')], max_length=500),
        ),
    ]
