# Generated by Django 2.2.6 on 2019-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0010_auto_20191108_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_need_OBGYN_services',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_need_help_with_other_mental_health_disorders',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_need_to_see_various_specialists',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_need_treatment_for_anxiety',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_need_treatment_for_depression',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_often_use_preventative_services',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Do_you_want_to_keep_your_current_doctor',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Is_emergency_care_or_hospital_care_a_priority',
        ),
        migrations.AddField(
            model_name='questions',
            name='Are_you_diagnosed_with_a_mental_health_condition',
            field=models.CharField(blank=True, choices=[('40OSIS', 'Yes'), ('41', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_come_in_for_annual_mammogram_or_prostate_exams',
            field=models.CharField(blank=True, choices=[('42DT', 'Yes'), ('43', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_have_a_labor_intensive_job',
            field=models.CharField(blank=True, choices=[('36IMA', 'Yes'), ('37', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_often_come_in_for_routine_checkups',
            field=models.CharField(blank=True, choices=[('14PC', 'Yes'), ('15', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_often_deal_with_skin_conditions',
            field=models.CharField(blank=True, choices=[('20S', 'Yes'), ('21', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_often_feel_chronic_pain',
            field=models.CharField(blank=True, choices=[('38RS', 'Yes'), ('39', 'No')], max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='Do_you_often_participate_in_sports',
            field=models.CharField(blank=True, choices=[('24IMARS', 'Yes'), ('25', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='DiagnosticTest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='GenericDrugs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='HomeHealthCare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='ImmediateMedicalAttention',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='OutpatientInpatient',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='OutpatientSurgery',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='Pregnancy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='PreventativeCare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='RehabilationServices',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='SkilledNursingCare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcare_categories',
            name='SpecialistServices',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_cataract_surgery',
            field=models.CharField(blank=True, choices=[('44OS', 'Yes'), ('45', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_hip_replacement',
            field=models.CharField(blank=True, choices=[('48HHC', 'Yes'), ('49', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_a_candidate_for_knee_replacement',
            field=models.CharField(blank=True, choices=[('46HHC', 'Yes'), ('47', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_currently_taking_pescribed_medication',
            field=models.CharField(blank=True, choices=[('8GD', 'Yes'), ('9', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diabetic',
            field=models.CharField(blank=True, choices=[('32S', 'Yes'), ('33', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diagnosed_with_cancer',
            field=models.CharField(blank=True, choices=[('28SNC', 'Yes'), ('29', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_diagnosed_with_heart_disease',
            field=models.CharField(blank=True, choices=[('26OSSNC', 'Yes'), ('27', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Are_you_pregnant',
            field=models.CharField(blank=True, choices=[('30P', 'Yes'), ('31', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_get_routine_vaccines_or_flu_shots',
            field=models.CharField(blank=True, choices=[('12PC', 'Yes'), ('13', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_help_with_substance_abuse',
            field=models.CharField(blank=True, choices=[('34OSIS', 'Yes'), ('35', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_prenatal_maternity_services',
            field=models.CharField(blank=True, choices=[('16P', 'Yes'), ('17', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_need_treatement_for_HIV_or_Aids',
            field=models.CharField(blank=True, choices=[('18GD', 'Yes'), ('19', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Do_you_receive_regular_physicals_and_health_screenings',
            field=models.CharField(blank=True, choices=[('10DT', 'Yes'), ('11', 'No')], max_length=500),
        ),
    ]
