# Generated by Django 3.0.1 on 2020-03-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0014_auto_20200316_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='Gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Non-Binary')], default='Male', max_length=500),
        ),
    ]
