# Generated by Django 3.0.1 on 2020-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0016_auto_20200316_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Non-Binary')], max_length=500),
        ),
    ]
