# Generated by Django 3.0.1 on 2020-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0017_auto_20200317_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Non-Binary')], default='Unspecified', max_length=500),
        ),
    ]
