# Generated by Django 3.0.1 on 2020-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0019_auto_20200317_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Depression', 'Depression'), ('Heart Issues', 'Heart Issues')], max_length=100)),
            ],
        ),
    ]
