# Generated by Django 3.0.1 on 2020-03-17 17:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0020_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='title',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='Please_choose_all_that_apply',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Depression', 'Depression'), ('Heart Issues', 'Heart Issues')], default='Unspecified', max_length=100),
        ),
    ]
