from django.db import models


class HealthPlan(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField('date added')
    Overall_deductible_person= models.IntegerField(max_length=10)
    Overall_deductible_family= models.IntegerField(max_length=10)
    Out_of_pocket_limit_person= models.IntegerField(max_length=10)
    Out_of_pocket_limit_family= models.IntegerField(max_length=10)
    Primary_care_visit = models.IntegerField(max_length=10)
    Specialist_visit = models.IntegerField(max_length=10)
    Diagnostic_test_lab = models.IntegerField(max_length=10)
    Diagnostic_test_xray = models.IntegerField(max_length=10)
    Imaging = models.IntegerField(max_length=10)
    Generic_drugs_pescrciption = models.IntegerField(max_length=10)
    Preffered_drugs_pescrciption = models.IntegerField(max_length=10)
    Facility_fee = models.IntegerField(max_length=10)
    Physician_surgeon_fee = models.IntegerField(max_length=10)
    Emergency_room_care_IMA = models.IntegerField(max_length=10)
    Emergency_medical_transportation_IMA = models.IntegerField(max_length=10)
    Urgent_care_IMA = models.IntegerField(max_length=10)
    Emergency_room_care_Hospital_Stay = models.IntegerField(max_length=10)
    Emergency_medical_transportation_HospitalStay = models.IntegerField(max_length=10)
    Outpatient_services = models.IntegerField(max_length=10)
    Inpatient_services = models.IntegerField(max_length=10)
    Pregnant_childbirth_delivery_professional_services = models.IntegerField(max_length=10)
    Pregnant_childbirth_delivery_facility_services = models.IntegerField(max_length=10)
    Pregnant_office_visit = models.IntegerField(max_length=10)
    Home_health_care = models.IntegerField(max_length=10)
    Rehabilitation_services = models.IntegerField(max_length=10)
    Skilled_nursing_care = models.IntegerField(max_length=10)
    Durable_medical_eqiupment = models.IntegerField(max_length=10)
    def __str__(self):
        return self.name
