from django.db import models


class HealthPlan(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField('date added')
    Overall_deductible_person= models.IntegerField()
    Overall_deductible_family= models.IntegerField()
    Out_of_pocket_limit_person= models.IntegerField()
    Out_of_pocket_limit_family= models.IntegerField()
    Primary_care_visit = models.IntegerField()
    Specialist_visit = models.IntegerField()
    Diagnostic_test_lab = models.IntegerField()
    Diagnostic_test_xray = models.IntegerField()
    Imaging = models.IntegerField()
    Generic_drugs_pescrciption = models.IntegerField()
    Preffered_drugs_pescrciption = models.IntegerField()
    Facility_fee = models.IntegerField()
    Physician_surgeon_fee = models.IntegerField()
    Emergency_room_care_IMA = models.IntegerField()
    Emergency_medical_transportation_IMA = models.IntegerField()
    Urgent_care_IMA = models.IntegerField()
    Emergency_room_care_HospitalStay = models.IntegerField()
    Emergency_medical_transportation_HospitalStay = models.IntegerField()
    Outpatient_services = models.IntegerField()
    Inpatient_services = models.IntegerField()
    Pregnant_childbirth_delivery_professional_services = models.IntegerField()
    Pregnant_childbirth_delivery_facility_services = models.IntegerField()
    Pregnant_office_visit = models.IntegerField()
    Home_health_care = models.IntegerField()
    Rehabilitation_services = models.IntegerField()
    Skilled_nursing_care = models.IntegerField()
    Durable_medical_eqiupment = models.IntegerField()